//
//          Copyright Seth Hendrick 2016-2021.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)
//

// .cs IS AN AUTOGENERATED FILE, ONLY EDIT THE .cs.template FILE, OR THIS WILL BE OVERWRITTEN!

namespace Chaskis.RegressionTests.TestCore
{
    /// <summary>
    /// Constants that are filled in during the template time-frame.
    /// </summary>
    public class ChaskisConstants
    {
        /// <summary>
        /// Expected version of Chaskis.exe.
        /// </summary>
        internal const string ExpectedChaskisExeVersion = "0.31.0";

        /// <summary>
        /// Expected version of Chaskis.Core.
        /// </summary>
        internal const string ExpectedChaskisCoreVersion = "0.31.0";

        /// <summary>
        /// Expected default plugin name of Chaskis.
        /// </summary>
        internal const string ExpectedDefaultPluginName = "chaskis";

        /// <summary>
        /// Expected name of the regression test plugin.
        /// </summary>
        internal const string ExpectedRegressionTestPluginName = "chaskistests";

        /// <summary>
        /// Expected version of the regression test plugin.
        /// </summary>
        internal const string ExpectedRegressionTestPluginVersion = "1.0.0";

        /// <summary>
        /// Expected URL to the project (GitHub).
        /// </summary>
        internal const string ExpectedProjectUrl = "https://github.com/xforever1313/Chaskis/";

        /// <summary>
        /// Expected URL Chaskis's License File on GitHub.
        /// </summary>
		internal const string ExpectedLicenseUrl = "https://github.com/xforever1313/Chaskis/blob/master/LICENSE_1_0.txt";
    }
}
